name: geocode
version: 1.0.0-nullsafety.0
homepage: https://github.com/imvalient/geocode
repository: https://github.com/imvalient/geocode
description: >-
    Package to make Geocode requests. It exposes two methods to translate
    coordinates into locations and addresses into coordinates.

environment:
    sdk: ">=2.12.0-0 <3.0.0"

dependencies:
    http:
        git:
            url: https://github.com/dart-lang/http
            ref: d473635f0dbb72936664696162127c2209986356 # Stable & tested master branch commit.
dev_dependencies:
  test: ^1.16.0-nullsafety.4

dependency_overrides:
  http_parser: ^4.0.0-nullsafety
  # Because pkg:test does not support pkg:http ^0.13.0
  test: ^1.16.0-nullsafety.5