name: geocode
description: >-
    Package to make Geocode requests. It exposes two methods to translate
    coordinates into locations and addresses into coordinates.
version: 0.1.0

environment:
    sdk: ">=2.3.0 <3.0.0"

dependencies:
    http: ^0.12.2

dev_dependencies:
    test: ^1.15.3